version: "2"

run:
  tests: false
  modules-download-mode: readonly
  timeout: 1m
  allow-parallel-runners: true

linters:
  enable:
    - wrapcheck
    - bodyclose
    - copyloopvar
    - durationcheck
    - gocyclo
    - gosec
    - misspell
    - mnd
    - noctx
    - unparam
    - wastedassign
    - gocritic

  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
  